<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEDbVvml\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEDbVvml/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEDbVvml.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEDbVvml\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEDbVvml\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EDbVvml',
    'container.build_id' => '7184bfb3',
    'container.build_time' => 1616606302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEDbVvml');
