<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2XQVXqh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2XQVXqh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2XQVXqh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2XQVXqh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2XQVXqh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2XQVXqh',
    'container.build_id' => 'ee815f59',
    'container.build_time' => 1615509199,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2XQVXqh');
