<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPCM1Dt0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPCM1Dt0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPCM1Dt0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPCM1Dt0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPCM1Dt0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PCM1Dt0',
    'container.build_id' => '7f3e4b74',
    'container.build_time' => 1616059774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPCM1Dt0');
